### ISSUE TITLE
Build fails on Node.js v0.10.2

### ISSUE THREAD

**Issue by whitelynx** [w1nk/node-odbc#34]
It looks like the definition of `uv_after_work_cb` has changed...

```
gyp info it worked if it ends with ok
gyp info using node-gyp@0.9.5
gyp info using node@0.10.2 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/home/dbronke/devel/other/node-odbc/build'
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
../src/odbc.cpp: In static member function ‘static v8::Handle<v8::Value> ODBC::Open(const v8::Arguments&)’:
../src/odbc.cpp:306:67: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
In file included from /home/dbronke/.node-gyp/0.10.2/src/node.h:61:0,
                 from ../src/odbc.cpp:19:
/home/dbronke/.node-gyp/0.10.2/deps/uv/include/uv.h:1411:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
../src/odbc.cpp: In static member function ‘static v8::Handle<v8::Value> ODBC::Close(const v8::Arguments&)’:
../src/odbc.cpp:383:69: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
In file included from /home/dbronke/.node-gyp/0.10.2/src/node.h:61:0,
                 from ../src/odbc.cpp:19:
/home/dbronke/.node-gyp/0.10.2/deps/uv/include/uv.h:1411:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
../src/odbc.cpp: In static member function ‘static void ODBC::UV_AfterQuery(uv_work_t*)’:
../src/odbc.cpp:399:13: warning: unused variable ‘ret’ [-Wunused-variable]
../src/odbc.cpp: In static member function ‘static v8::Handle<v8::Value> ODBC::Query(const v8::Arguments&)’:
../src/odbc.cpp:599:69: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
In file included from /home/dbronke/.node-gyp/0.10.2/src/node.h:61:0,
                 from ../src/odbc.cpp:19:
/home/dbronke/.node-gyp/0.10.2/deps/uv/include/uv.h:1411:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
../src/odbc.cpp: In static member function ‘static v8::Handle<v8::Value> ODBC::QueryAll(const v8::Arguments&)’:
../src/odbc.cpp:932:75: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
In file included from /home/dbronke/.node-gyp/0.10.2/src/node.h:61:0,
                 from ../src/odbc.cpp:19:
/home/dbronke/.node-gyp/0.10.2/deps/uv/include/uv.h:1411:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
../src/odbc.cpp: In static member function ‘static v8::Handle<v8::Value> ODBC::Tables(const v8::Arguments&)’:
../src/odbc.cpp:1007:73: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
In file included from /home/dbronke/.node-gyp/0.10.2/src/node.h:61:0,
                 from ../src/odbc.cpp:19:
/home/dbronke/.node-gyp/0.10.2/deps/uv/include/uv.h:1411:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
../src/odbc.cpp: In static member function ‘static v8::Handle<v8::Value> ODBC::Columns(const v8::Arguments&)’:
../src/odbc.cpp:1080:74: error: invalid conversion from ‘void (*)(uv_work_t*) {aka void (*)(uv_work_s*)}’ to ‘uv_after_work_cb {aka void (*)(uv_work_s*, int)}’ [-fpermissive]
In file included from /home/dbronke/.node-gyp/0.10.2/src/node.h:61:0,
                 from ../src/odbc.cpp:19:
/home/dbronke/.node-gyp/0.10.2/deps/uv/include/uv.h:1411:15: error:   initializing argument 4 of ‘int uv_queue_work(uv_loop_t*, uv_work_t*, uv_work_cb, uv_after_work_cb)’ [-fpermissive]
../src/odbc.cpp: In static member function ‘static v8::Handle<v8::Value> ODBC::GetColumnValue(SQLHSTMT, Column, uint16_t*, int)’:
../src/odbc.cpp:1151:28: warning: missing initializer for member ‘tm::tm_min’ [-Wmissing-field-initializers]
../src/odbc.cpp:1151:28: warning: missing initializer for member ‘tm::tm_hour’ [-Wmissing-field-initializers]
../src/odbc.cpp:1151:28: warning: missing initializer for member ‘tm::tm_mday’ [-Wmissing-field-initializers]
../src/odbc.cpp:1151:28: warning: missing initializer for member ‘tm::tm_mon’ [-Wmissing-field-initializers]
../src/odbc.cpp:1151:28: warning: missing initializer for member ‘tm::tm_year’ [-Wmissing-field-initializers]
../src/odbc.cpp:1151:28: warning: missing initializer for member ‘tm::tm_wday’ [-Wmissing-field-initializers]
../src/odbc.cpp:1151:28: warning: missing initializer for member ‘tm::tm_yday’ [-Wmissing-field-initializers]
../src/odbc.cpp:1151:28: warning: missing initializer for member ‘tm::tm_isdst’ [-Wmissing-field-initializers]
../src/odbc.cpp:1151:28: warning: missing initializer for member ‘tm::tm_gmtoff’ [-Wmissing-field-initializers]
../src/odbc.cpp:1151:28: warning: missing initializer for member ‘tm::tm_zone’ [-Wmissing-field-initializers]
make: *** [Release/obj.target/odbc_bindings/src/odbc.o] Error 1
make: Leaving directory `/home/dbronke/devel/other/node-odbc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dbronke/devel/other/node-odbc/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:757:12)
gyp ERR! System Linux 3.7.10-1-ARCH
gyp ERR! command "node" "/home/dbronke/devel/other/node-odbc/node_modules/node-gyp/bin/node-gyp.js" "build"
gyp ERR! cwd /home/dbronke/devel/other/node-odbc
gyp ERR! node -v v0.10.2
gyp ERR! node-gyp -v v0.9.5
gyp ERR! not ok 
```

**Comment by whitelynx** [comment]
Looks like this changed on one of the upgrades of libuv in node: https://github.com/joyent/node/commit/6cf68aead6886d397772ea176a9f5c35fdb63071#L6R329

I'm not familiar with gyp, but I'm relatively proficient with waf... I could try adding a check for this in the `wscript`.

**Comment by whitelynx** [comment]
Actually, I can't get this to build with `waf`. I'm not sure what version was used when the `wscript` was created, but it won't work with the latest. Most projects that use `waf` are encouraged to include `waf` directly in their source, which avoids this issue. (see [Why is packaging of waf in distributions discouraged?](https://code.google.com/p/waf/wiki/FAQ#Why_is_packaging_of_waf_in_distributions_discouraged?)) Should I open another issue to include `waf` in the source?

**Comment by wankdanker** [comment]
I am working on this issue right now. If you want to create a separate issue for `waf` that's fine. I doubt that it will get addressed though. Last I knew module maintainers were supposed to be steering away from `waf` towards `gyp`. I haven't been paying attention lately though, so I may be out of the loop.

I believe this particular issue is related to a change in the definition of `uv_queue_work` as you pointed out (https://github.com/joyent/node/wiki/Api-changes-between-v0.8-and-v0.10) :

> The uv_after_work_cb signature has changed to take a second integer argument indicating status. For backwards compatibility, explicitly cast the 4th argument to uv_queue_work. 

Once I get this fixed, I will post back here and provide a link to test it from my github branch. I like to run changes in my environment for a while before I publish to npm.

Thanks for the report, @whitelynx.

**Comment by whitelynx** [comment]
Aah, ok... my pull request actually just added overloads to each of the `UV_After*` methods that call the original methods, discarding the `status` argument. It compiles and works for me, and all but 2 of the tests run fine (those being `test-date` which fails because `SELECT cast('2013-04-02T17:16:19.334' as datetime) as DT1` returns `2013` in sqlite3 on my system, and `test-open-dont-close` which times out, but it looks like that's what the test is designed to do) but if they suggest a different way of doing it, it probably makes sense to follow that instead.

**Comment by wankdanker** [comment]
If you would like to test this, try installing with:

``` bash
npm install git://github.com/wankdanker/node-odbc.git#v0.5
```

**Comment by whitelynx** [comment]
Yep, that works here. Thanks!
