### ISSUE TITLE
Odbc not compliant with nodeJs 0.10

### ISSUE THREAD

**Issue by jcamus** [w1nk/node-odbc#35]
When running my application using latest node-odbc and with node runtime 0.10.3, I have the following error :

module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: Module version mismatch. Expected 11, got 1.
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/jcamus/myModule/node_modules/odbc/odbc.js:25:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by wankdanker** [comment]
The error you posted (module version mismatch) indicates that `node-odbc` hasn't been recompiled since node was upgraded to v0.10. However, if you had tried to rebuild, it would have failed anyway. I just pushed out node-odbc v0.4.4 which contains the fix for the compiling failure.

Try re-installing with:

``` bash
npm install odbc@latest
```

Hope this helps.

**Comment by jcamus** [comment]
Ok thanks a lot! It works fine! Good work! ;-)
