### ISSUE TITLE
Error running the script

### ISSUE THREAD

**Issue by user1020** [w1nk/node-odbc#58]
Thanks for writing this module.    After I installed it (from this repo) and ran the sample script, got error.   Wonder why.

```
var util = require('util');
var odbc = require("odbc");

var db = new odbc.Database();
db.open("DRIVER={FreeTDS};SERVER=host;UID=user;PWD=password;DATABASE=dbname", function(err)
{
    db.query("select * from table", function(err, rows, moreResultSets)
    {
        util.debug(util.inspect(rows));
        db.close(function(){});
    });
});
```

```
module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/jin1/projs/nodeSrv/node_modules/odbc/build/Release/odbc_bindings.node: undefined symbol: ev_default_loop_ptr
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/jin1/projs/nodeSrv/node_modules/odbc/odbc.js:25:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by wankdanker** [comment]
What version of node? Did you try installing with `npm install odbc`?

**Comment by user1020** [comment]
My node version is v0.10.26, I did use "npm install odbc".  My PC is Unbuntu 12.04, not sure if this is a problem.  Thanks.

**Comment by wankdanker** [comment]
That error is indicative of an older version of node-odbc being installed and used with a newer version of node. Please report the output of the following commands:

``` bash
$ grep -Ri ev_default_loop_ptr /home/jin1/projs/nodeSrv/node_modules/odbc
```

``` bash
$ cd /home/jin1/projs/nodeSrv
$ npm ls
```

Thanks,

Dan

**Comment by user1020** [comment]
```
grep -Ri ev_default_loop_ptr /home/jin1/projs/nodeSrv/node_modules/odbc
Binary file /home/jin1/projs/nodeSrv/node_modules/odbc/build/Release/odbc_bindings.node matches
Binary file /home/jin1/projs/nodeSrv/node_modules/odbc/build/Release/src/Database_1.o matches
```

I have a ton of modules installed,  here is the version of odbc, 

```
 npm ls odbc
/home/jin1/projs/nodeSrv
└── odbc@0.3.1  (git://github.com/w1nk/node-odbc.git#f6c877a954f08ba8ac22e777bef424e0dba1364b)
```

If you need the whole list (very long), please let me know.

Thanks.

**Comment by wankdanker** [comment]
Perfect. That version of node-odbc is way old. Try installing with `npm install odbc@0.6.4`.

**Comment by user1020** [comment]
Thanks Dan. After installing the newer version, don't see the crash any more.

**Comment by wankdanker** [comment]
Awesome. Glad to hear it. Enjoy.
