### ISSUE TITLE
Error: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by kbjr** [w1nk/node-odbc#72]
I'm getting this error just by requiring the module. The stack trace is here:

```
Error: %1 is not a valid Win32 application.
c:\...\node_modules\odbc\build\Release\odbc_bindings.node
    at Error (native)
    at Module.load (module.js:352:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:360:17)
    at require (module.js:376:17)
    at bindings (C:\...\node_modules\odbc\node_modules\bindings\bindings.js:74:15)
    at Object.<anonymous> (C:\...\node_modules\odbc\lib\odbc.js:18:31)
    at Module._compile (module.js:452:26)
    at Object.Module._extensions..js (module.js:470:10)
    at Module.load (module.js:352:32)
```

This is running on Windows 7 64-bit. Node v0.10.30

**Comment by CoDEmanX** [comment]
Did you compile the module yourself?

**Comment by kbjr** [comment]
I don't remember the specifics, this was a while ago and we ended up using a different module. I want to say that this was installed using `npm install`, not by any manual process.

**Comment by cosmin-novac** [comment]
Hi kbjr, would you be so kind and tell us what module you ended up using?

**Comment by kbjr** [comment]
I believe we ended up using [node-adodb](https://www.npmjs.com/package/node-adodb)
